# Remplacement de {{ wordpress_instance_ip }} par adresse IP de sortie tf
- hosts: "{ wordpress_instance_ip }" 
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install PHP and required modules
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php
        - libapache2-mod-php
        - php-mysql

    # Autres tâches d'installation et de configuration spécifiques à WordPress
    # Assurez-vous de configurer les fichiers de configuration de WordPress

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

